-- =========================================
-- PARKING MANAGEMENT SYSTEM - QUERIES
-- =========================================

-- 1. Check project tables
SELECT table_name
FROM user_tables
WHERE table_name IN ('AREA','VEHICLE','SLOT','TRACKING','FEE','PARKING_UNNORMALIZED')
ORDER BY table_name;


-- 2. Display parking unnormalized data
SELECT * FROM PARKING_UNNORMALIZED;


-- 3. Display area data
SELECT * FROM AREA;


-- 4. Display vehicle data
SELECT * FROM VEHICLE;


-- 5. Display slot data
SELECT * FROM SLOT;


-- 6. Display tracking data
SELECT * FROM TRACKING;


-- 7. Display fee data
SELECT * FROM FEE;


-- 8. Count tracking records for each vehicle
SELECT VEHICLEID, COUNT(*)
FROM TRACKING
GROUP BY VEHICLEID;


-- 9. Count total vehicles
SELECT COUNT(*) AS TOTAL_VEHICLES
FROM VEHICLE;


-- 10. Count vehicles by type
SELECT VTYPE, COUNT(*) AS TOTAL_VEHICLES
FROM VEHICLE
GROUP BY VTYPE
ORDER BY TOTAL_VEHICLES DESC;


-- 11. Count slots by status
SELECT SLOTSTATUS, COUNT(*) AS TOTAL_SLOTS
FROM SLOT
GROUP BY SLOTSTATUS;


-- 12. Calculate total parking revenue
SELECT SUM(TOTALFEE) AS TOTAL_REVENUE
FROM FEE;


-- 13. Calculate average parking fee
SELECT AVG(TOTALFEE) AS AVERAGE_FEE
FROM FEE;


-- 14. Find highest parking fee
SELECT MAX(TOTALFEE) AS HIGHEST_FEE
FROM FEE;


-- 15. Find lowest parking fee
SELECT MIN(TOTALFEE) AS LOWEST_FEE
FROM FEE;


-- 16. Show parking fees above 100
SELECT *
FROM FEE
WHERE TOTALFEE > 100
ORDER BY TOTALFEE DESC;


-- 17. Show vehicles of a specific type
SELECT *
FROM VEHICLE
WHERE VTYPE = 'Car';


-- 18. Show available parking slots
SELECT *
FROM SLOT
WHERE SLOTSTATUS = 'Available';


-- 19. Show occupied parking slots
SELECT *
FROM SLOT
WHERE SLOTSTATUS = 'Occupied';


-- 20. Show tracking records with duration greater than 5 hours
SELECT *
FROM TRACKING
WHERE DURATIONHRS > 5
ORDER BY DURATIONHRS DESC;


-- 21. Show areas with capacity greater than 50
SELECT *
FROM AREA
WHERE CAPACITY > 50
ORDER BY CAPACITY DESC;


-- 22. Show fees by hourly rate
SELECT HOURLYRATE, COUNT(*) AS NUMBER_OF_RECORDS
FROM FEE
GROUP BY HOURLYRATE
ORDER BY HOURLYRATE;


-- 23. Shows which vehicles used which parking slots
SELECT
    V.VEHICLEID,
    V.PLATE,
    V.OWNERNAME,
    V.VTYPE,
    T.TRACKINGID,
    T.ENTRYTIME,
    T.EXITTIME,
    T.DURATIONHRS
FROM VEHICLE V
INNER JOIN TRACKING T
    ON V.VEHICLEID = T.VEHICLEID
ORDER BY T.ENTRYTIME DESC;


-- 24. Combines vehicle, area, slot, tracking and fee information
SELECT
    V.PLATE,
    V.OWNERNAME,
    V.VTYPE,
    A.AREANAME,
    S.SLOTID,
    T.ENTRYTIME,
    T.EXITTIME,
    T.DURATIONHRS,
    F.HOURLYRATE,
    F.TOTALFEE
FROM VEHICLE V
JOIN TRACKING T
    ON V.VEHICLEID = T.VEHICLEID
JOIN SLOT S
    ON T.SLOTID = S.SLOTID
JOIN AREA A
    ON S.AREAID = A.AREAID
JOIN FEE F
    ON T.TRACKINGID = F.TRACKINGID
ORDER BY T.ENTRYTIME DESC;


-- 25. Revenue by parking area
SELECT
    A.AREANAME,
    COUNT(F.FEEID) AS TOTAL_TRANSACTIONS,
    SUM(F.TOTALFEE) AS TOTAL_REVENUE,
    AVG(F.TOTALFEE) AS AVERAGE_FEE
FROM AREA A
JOIN SLOT S
    ON A.AREAID = S.AREAID
JOIN TRACKING T
    ON S.SLOTID = T.SLOTID
JOIN FEE F
    ON T.TRACKINGID = F.TRACKINGID
GROUP BY A.AREANAME
ORDER BY TOTAL_REVENUE DESC;


-- 26. Revenue by vehicle type
SELECT
    V.VTYPE,
    COUNT(F.FEEID) AS TOTAL_TRANSACTIONS,
    SUM(F.TOTALFEE) AS TOTAL_REVENUE,
    AVG(F.TOTALFEE) AS AVERAGE_FEE
FROM VEHICLE V
JOIN TRACKING T
    ON V.VEHICLEID = T.VEHICLEID
JOIN FEE F
    ON T.TRACKINGID = F.TRACKINGID
GROUP BY V.VTYPE
ORDER BY TOTAL_REVENUE DESC;


-- 27. Parking duration category using CASE
SELECT
    T.TRACKINGID,
    V.PLATE,
    T.DURATIONHRS,
    CASE
        WHEN T.DURATIONHRS < 2 THEN 'Short Stay'
        WHEN T.DURATIONHRS BETWEEN 2 AND 5 THEN 'Medium Stay'
        ELSE 'Long Stay'
    END AS PARKING_CATEGORY
FROM TRACKING T
JOIN VEHICLE V
    ON T.VEHICLEID = V.VEHICLEID
ORDER BY T.DURATIONHRS DESC;


-- 28. Vehicles with above-average parking duration
SELECT
    V.PLATE,
    V.OWNERNAME,
    T.DURATIONHRS
FROM VEHICLE V
JOIN TRACKING T
    ON V.VEHICLEID = T.VEHICLEID
WHERE T.DURATIONHRS > (
    SELECT AVG(DURATIONHRS)
    FROM TRACKING
)
ORDER BY T.DURATIONHRS DESC;


-- 29. Fees above the average parking fee
SELECT
    F.FEEID,
    F.TRACKINGID,
    F.TOTALFEE
FROM FEE F
WHERE F.TOTALFEE > (
    SELECT AVG(TOTALFEE)
    FROM FEE
)
ORDER BY F.TOTALFEE DESC;


-- 30. Areas with above average capacity
SELECT
    AREANAME,
    CAPACITY
FROM AREA
WHERE CAPACITY > (
    SELECT AVG(CAPACITY)
    FROM AREA
)
ORDER BY CAPACITY DESC;


-- 31. CTE for area revenue
WITH AREA_REVENUE AS (
    SELECT
        A.AREAID,
        A.AREANAME,
        SUM(F.TOTALFEE) AS TOTAL_REVENUE
    FROM AREA A
    JOIN SLOT S
        ON A.AREAID = S.AREAID
    JOIN TRACKING T
        ON S.SLOTID = T.SLOTID
    JOIN FEE F
        ON T.TRACKINGID = F.TRACKINGID
    GROUP BY A.AREAID, A.AREANAME
)
SELECT
    AREANAME,
    TOTAL_REVENUE
FROM AREA_REVENUE
ORDER BY TOTAL_REVENUE DESC;


-- 32. CTE for average duration by vehicle type
WITH VEHICLE_DURATION AS (
    SELECT
        V.VTYPE,
        AVG(T.DURATIONHRS) AS AVG_DURATION
    FROM VEHICLE V
    JOIN TRACKING T
        ON V.VEHICLEID = T.VEHICLEID
    GROUP BY V.VTYPE
)
SELECT
    VTYPE,
    ROUND(AVG_DURATION, 2) AS AVG_DURATION_HOURS
FROM VEHICLE_DURATION
ORDER BY AVG_DURATION DESC;


-- 33.  Rank vehicles by total parking expenditure
SELECT
    V.PLATE,
    V.OWNERNAME,
    SUM(F.TOTALFEE) AS TOTAL_SPENDING,
    RANK() OVER (
        ORDER BY SUM(F.TOTALFEE) DESC
    ) AS SPENDING_RANK
FROM VEHICLE V
JOIN TRACKING T
    ON V.VEHICLEID = T.VEHICLEID
JOIN FEE F
    ON T.TRACKINGID = F.TRACKINGID
GROUP BY
    V.PLATE,
    V.OWNERNAME
ORDER BY SPENDING_RANK;


-- 34. Rank vehicles within each vehicle type
SELECT
    V.VTYPE,
    V.PLATE,
    SUM(F.TOTALFEE) AS TOTAL_SPENDING,
    RANK() OVER (
        PARTITION BY V.VTYPE
        ORDER BY SUM(F.TOTALFEE) DESC
    ) AS TYPE_RANK
FROM VEHICLE V
JOIN TRACKING T
    ON V.VEHICLEID = T.VEHICLEID
JOIN FEE F
    ON T.TRACKINGID = F.TRACKINGID
GROUP BY
    V.VTYPE,
    V.PLATE
ORDER BY
    V.VTYPE,
    TYPE_RANK;
    
    
-- 35. Running revenue total
SELECT
    F.FEEID,
    T.ENTRYTIME,
    F.TOTALFEE,
    SUM(F.TOTALFEE) OVER (
        ORDER BY T.ENTRYTIME
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS RUNNING_REVENUE
FROM FEE F
JOIN TRACKING T
    ON F.TRACKINGID = T.TRACKINGID
ORDER BY T.ENTRYTIME;


    
    